#!/bin/bash

# Check if ngrok is running
if ! curl -s http://localhost:4040/api/tunnels > /dev/null; then
    echo "Error: ngrok doesn't appear to be running. Please start it first."
    exit 1
fi

# Get public URL from ngrok
ngrok_url=$(curl -s http://localhost:4040/api/tunnels | grep -o '"public_url":"[^"]*' | grep -o 'https://[^"]*')

if [ -z "$ngrok_url" ]; then
    echo "Error: Couldn't get ngrok URL. Please check the ngrok dashboard at http://localhost:4040"
    exit 1
fi

# Create or update .env.local
echo "# Auto-generated by update-env.sh" > .env.local
echo "VITE_API_URL=${ngrok_url}/api" >> .env.local

echo "======================================================"
echo "✅ Environment updated with ngrok URL"
echo "Frontend will use API at: ${ngrok_url}/api"
echo "======================================================"
echo "To apply these changes, restart your frontend development server"
echo "======================================================" 