// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shbcgskjphdhhgizlxvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoYmNnc2tqcGhkaGhnaXpseHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjg1NzQsImV4cCI6MjA2MjYwNDU3NH0.pBH6hoJ578c3BPqNp-vRKFqTKW7ewKNu0U8pYOaCuec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);